question 1)

In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 6, 4, 5])
print(a[::-1])

[5 4 6 3 2 1]


In [5]:
b = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(b.flatten())
print(b.ravel())

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [6]:
c1 = np.array([[1, 2], [3, 4]])
c2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(c1, c2))
print(c1 == c2)

True
[[ True  True]
 [ True  True]]


In [7]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
v = np.bincount(x)
m = np.argmax(v)
print(m)
print(np.where(x == m)[0])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
v = np.bincount(y)
m = np.argmax(v)
print(m)
print(np.where(y == m)[0])

1
[0 5 7 8 9]
1
[0 1 2]


In [8]:
g = np.matrix('[4,1,9;12,3,1;4,5,6]')
print(np.sum(g))
print(np.sum(g, axis=1))
print(np.sum(g, axis=0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [9]:
n = np.array([[55, 25, 15],
              [30, 44, 2],
              [11, 45, 77]])

print(np.trace(n))
print(np.linalg.eigvals(n))
w, v = np.linalg.eig(n)
print(v)
print(np.linalg.inv(n))
print(np.linalg.det(n))

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [10]:
p = np.array([[1, 2],
              [2, 3]])
q = np.array([[4, 5],
              [6, 7]])

print(np.matmul(p, q))
print(np.cov(p, q))

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [11]:
p = np.array([[1, 2],
              [2, 3],
              [4, 5]])
q = np.array([[4, 5, 1],
              [6, 7, 2]])

print(np.matmul(p, q))
print(np.cov(p.T, q))

[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]


In [12]:
x = np.array([[2, 3, 4],
              [3, 2, 9]])

y = np.array([[1, 5, 0],
              [5, 10, 3]])

print(np.inner(x, y))
print(np.outer(x, y))
print(np.transpose([np.repeat(x.flatten(), len(y.flatten())),
                    np.tile(y.flatten(), len(x.flatten()))]))

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


question 2)

In [13]:
a = np.array([[1, -2, 3],
              [-4, 5, -6]])

print(np.abs(a))

print(np.percentile(a, [25, 50, 75]))
print(np.percentile(a, [25, 50, 75], axis=0))
print(np.percentile(a, [25, 50, 75], axis=1))

print(np.mean(a))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a, axis=1))

print(np.std(a))
print(np.std(a, axis=0))
print(np.std(a, axis=1))

[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5
[-1.5  1.5 -1.5]
[ 0.66666667 -1.66666667]
-0.5
[-1.5  1.5 -1.5]
[ 1. -4.]
3.8622100754188224
[2.5 3.5 4.5]
[2.05480467 4.78423336]


In [14]:
b = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

print(np.floor(b))
print(np.ceil(b))
print(np.trunc(b))
print(np.round(b))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


question 3)

In [15]:
a = np.array([10, 52, 62, 16, 16, 54, 453])

print(np.sort(a))
print(np.argsort(a))
print(np.sort(a)[:4])
print(np.sort(a)[-5:])

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [16]:
b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

print(b[b == b.astype(int)])
print(b[b != b.astype(int)])

[1. 2. 3. 2.]
[1.2 2.2]


question 5)

In [21]:
img_to_array("image.jpg")

RGB image saved as rgb_image.txt
[[210 219 228]
 [210 219 228]
 [210 219 228]
 ...
 [150 172 185]
 [150 172 185]
 [150 172 185]]


In [22]:
from PIL import Image

def img_to_array(path):
    img = Image.open(path)

    if img.mode == "RGB":
        a = np.array(img)
        np.savetxt("rgb_image.txt", a.reshape(-1, 3), fmt="%d")
        print("RGB image saved as rgb_image.txt")

        x = np.loadtxt("rgb_image.txt", dtype=int)
        print(x)

    else:
        img = img.convert("L")
        a = np.array(img)
        np.savetxt("gray_image.txt", a, fmt="%d")
        print("Gray image saved as gray_image.txt")

        x = np.loadtxt("gray_image.txt", dtype=int)
        print(x)

img_to_array("image.jpg")

RGB image saved as rgb_image.txt
[[210 219 228]
 [210 219 228]
 [210 219 228]
 ...
 [150 172 185]
 [150 172 185]
 [150 172 185]]
