Q1

In [ ]:
import numpy as np
array = np.array([10, 20, 30, 40, 50])
print("Original array: ", array)
print("Array + 2: ", array + 2)
print("Multiply ny 3: ", array * 3)
print("Division by 2: ", array / 2)

Original array:  [10 20 30 40 50]
Array + 2:  [12 22 32 42 52]
Multiply ny 3:  [ 30  60  90 120 150]
Division by 2:  [ 5. 10. 15. 20. 25.]


Q2(a)

In [ ]:
import numpy as np
arr = np.array([1,2,3,6,4,5])
print("Original array: ", arr)
print("Reversed array: ", arr[::-1])

Original array:  [1 2 3 6 4 5]
Reversed array:  [5 4 6 3 2 1]


Q2(b)(i)

In [ ]:
from types import MethodDescriptorType
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
print("Most frequent value: ", most_frequent)
print("Indices: ", np.where(x == most_frequent)[0])

Most frequent value:  1
Indices:  [0 5 7 8 9]


Q2(b)(ii)

In [ ]:
import numpy as np
y = np.array([1,1,1,2,3,4,2,4,3,3])
values, counts = np.unique(y, return_counts= True)
most_frequent = values[np.argmax(counts)]
print("Most frequent value: ", most_frequent)
print("Indices: ", np.where(y == most_frequent)[0])

Most frequent value:  1
Indices:  [0 1 2]


Q3

In [ ]:
import numpy as np
arr = np.array([[10, 20, 30],
               [40, 50, 60],
               [70, 80, 90]])
print("1st row 2nd column: ", arr[0,1])
print("3rd row 1st column: ", arr[2,0])

1st row 2nd column:  20
3rd row 1st column:  70


Q4

In [ ]:
import numpy as np
Aryan = np.linspace(10, 100, 25)

print("Array: ")
print(Aryan)

print("Dimensions: ", Aryan.ndim)
print("Shape: ", Aryan.shape)
print("Total elements: ", Aryan.size)
print("Data type: ", Aryan.dtype)
print("Total bytes: ", Aryan.nbytes)

reshaped_Aryan = Aryan.reshape(5, 5)
print("Transpose using reshape: ")
print(reshaped_Aryan.T)

Array: 
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions:  1
Shape:  (25,)
Total elements:  25
Data type:  float64
Total bytes:  200
Transpose using reshape: 
[[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]


Q5

In [ ]:
import numpy as np
ucs420_Aryan = np.array([[10, 20, 30, 40],
                         [50, 60, 70, 80],
                         [90, 15, 20, 35]])
print("Original Array: ")
print(ucs420_Aryan)

print("Mean: ", np.mean(ucs420_Aryan))
print("Median: ", np.median(ucs420_Aryan))
print("Maximum: ", np.max(ucs420_Aryan))
print("Minimum: ", np.min(ucs420_Aryan))
print("Unique Elements: ", np.unique(ucs420_Aryan))
reshaped_ucs420_Aryan = ucs420_Aryan.reshape(4,3)
print("Reshaped array:")
print(reshaped_ucs420_Aryan)

resized_ucs420_Aryan = np.resize(ucs420_Aryan, (2, 3))

print("Resized array:")
print(resized_ucs420_Aryan)

Original Array: 
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean:  43.333333333333336
Median:  37.5
Maximum:  90
Minimum:  10
Unique Elements:  [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
[[10 20 30]
 [40 50 60]]
