Q1

In [ ]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

corrected_temperature = np.add(temperature, 2)
print("Corrected temperatures:", corrected_temperature)

fahrenheit = np.add(np.multiply(corrected_temperature, 9 / 5), 32)
print("Temperatures in Fahrenheit:", fahrenheit)

readings = corrected_temperature[corrected_temperature > 32]
print("Readings greater than 32°C:", readings)

count = np.sum(corrected_temperature > 32)
print("Number of readings exceeding 32°C:", count)

# Vectorization: Performs operations on the entire NumPy array at once, avoiding explicit loops.
# Boolean indexing: Creates a Boolean condition for each element and selects only those satisfying the condition.

Corrected temperatures: [27 30 33 37 40 29 35 42]
Temperatures in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Number of readings exceeding 32°C: 5


Q2

In [ ]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("Total steps:", np.sum(steps))
print("Mean steps:", np.mean(steps))
print("Maximum steps:", np.max(steps))
print("Minimum steps:", np.min(steps))
print("Total steps for each day:", np.sum(steps, axis=0))
print("Total steps for each user:", np.sum(steps, axis=1))
position = np.unravel_index(np.argmax(steps), steps.shape)
print("Position of maximum steps:", position)

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Position of maximum steps: (np.int64(3), np.int64(2))


Q3

In [ ]:
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])
subset = original[1:5]
subset[0] = 999

print("Original after modifying subset:", original)
print("Subset:", subset)

copied = original[1:5].copy()
copied[0] = 500
print("Original after modifying copy:", original)
print("Copied array:", copied)

matrix = np.arange(1, 13).reshape(3, 4)
print("3 x 4 matrix:")
print(matrix)

print("First row:", matrix[0])
print("Last row:", matrix[-1])
print("Second column:", matrix[:, 1])
print("Rows 1-2 and columns 2-3:", matrix[0:2, 1:3])

flat_array = matrix.flatten()
ravel_array = matrix.ravel()
print("Flatten array:", flat_array)
print("Ravel array:", ravel_array)

ravel_array[0] = 1000
print("Original after modifying ravel:", matrix)
print("Ravel after modification:", ravel_array)

flat_array[1] = 2000
print("Original after modifying flatten:", matrix)
print("Flatten after modification:", flat_array)

print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Original after modifying subset: [  1 999   3   4   5   6]
Subset: [999   3   4   5]
Original after modifying copy: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]
3 x 4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3: [[2 3]
 [6 7]]
Flatten array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original after modifying ravel: [[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
Ravel after modification: [1000    2    3    4    5    6    7    8    9   10   11   12]
Original after modifying flatten: [[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
Flatten after modification: [   1 2000    3    4    5    6    7    8    9   10   11   12]
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


Q4

In [ ]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

print("Transpose of X:")
print(X.T)

XtX = X.T @ X
print("X transpose multiplied by X:")
print(XtX)

inverse = np.linalg.inv(XtX)
print("Inverse of X transpose multiplied by X:")
print(inverse)

beta = inverse @ X.T @ y
print("OLS coefficients:", beta)

print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])

"""
Sleep hours: The coefficient is approximately -0.1592.
In this fitted model, increasing sleep by one hour, while keeping the other features constant,is associated with a small decrease in the predicted assistance score.
Activity level: The coefficient is approximately 0.1408.
Increasing activity by one unit, with the other features fixed, increases the predicted score by approximately 0.1408.
Stress level: The coefficient is approximately 10.0630.
Increasing stress by one unit, with the other features fixed, increases the predicted score by approximately 10.063.
"""

new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("Predicted assistance score:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2
Transpose of X:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
X transpose multiplied by X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse of X transpose multiplied by X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
OLS coefficients: [-0.15921454  0.14083853 10.06302242]
Sleep coefficient: -0.1592145415946895
Activity coefficient: 0.14083852991906243
Stress coefficient: 10.063022422714587
Predicted assistance score: 75.27862544779117
